src/argus/htmx/incident/urls.py
from django.urls import path

from . import views, filter


app_name = "htmx"
urlpatterns = [
    path("", views.incident_list, name="incident-list"),
    path("<int:pk>/", views.incident_detail, name="incident-detail"),
    path("update/<str:action>/", views.incident_update, name="incident-update"),
    path("filter/", views.filter_form, name="incident-filter"),
    path("filter-list/", filter.FilterListView.as_view(), name="filter-list"),
    path("select-filter/", views.filter_select, name="select-filter"),
    path("filter-create/", views.create_filter, name="filter-create"),
    path("filter/delete/<int:pk>/", views.delete_filter, name="filter-delete"),
    path("filter/update/<int:pk>/", views.update_filter, name="filter-update"),
    path("filter/existing/", views.get_existing_filters, name="existing-filters"),
    path("search-tags/", views.search_tags, name="search-tags"),
]

src/argus/htmx/urls.py
from django.contrib.auth import views as django_auth_views
from django.urls import path, include

from .auth import views as auth_views
from .incident.urls import urlpatterns as incident_urls
from .timeslot.urls import urlpatterns as timeslot_urls
from .notificationprofile.urls import urlpatterns as notificationprofile_urls
from .plannedmaintenance.urls import urlpatterns as plannedmaintenance_urls
from .destination.urls import urlpatterns as destination_urls
from .user.urls import urlpatterns as user_urls
from .views import IncidentListRedirectView, StyleGuideView

app_name = "htmx"
urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", django_auth_views.LogoutView.as_view(), name="logout"),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("styleguide/", StyleGuideView.as_view(), name="styleguide"),
    path("incidents/", include(incident_urls)),
    path("timeslots/", include(timeslot_urls)),
    path("notificationprofiles/", include(notificationprofile_urls)),
    path("plannedmaintenance/", include(plannedmaintenance_urls)),
    path("destinations/", include(destination_urls)),
    path("user/", include(user_urls)),
    path("", IncidentListRedirectView.as_view(), name="root"),
]

src/argus/htmx/incident/forms/base.py
from typing import Any, Optional
from urllib.parse import urlencode

from django import forms
from django.http import QueryDict

from argus.auth.utils import get_or_update_preference, get_preference


class IncidentListForm(forms.Form):
    fieldname: str
    field_initial: Any
    widget_classes: str = ""
    widget_template_name: Optional[str] = None
    lookup: Optional[str] = None  # used by filter method
    placeholder: str = ""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.widget_template_name:
            self.fields[self.fieldname].widget.template_name = self.widget_template_name
        self.fields[self.fieldname].widget.attrs["class"] = self.widget_classes
        self.fields[self.fieldname].widget.attrs["placeholder"] = self.placeholder

    def get_clean_value(self, request):
        value = self.get_initial_value(request)
        if self.is_valid():
            value = self.cleaned_data[self.fieldname]
        return value

    def get_querydict_for_value(self, request):
        data = {self.fieldname: self.get_clean_value(request)}
        return QueryDict(urlencode(data, doseq=True))

    def filter(self, queryset, request):
        return queryset

    @classmethod
    def _get_initial_preference_value(cls, request, namespace):
        return get_preference(request, namespace, cls.fieldname) or cls.field_initial

    @classmethod
    def _get_initial_session_value(cls, request):
        return request.session.get(cls.fieldname, cls.field_initial) or cls.field_initial

    @classmethod
    def get_initial_value(cls, request):
        return cls.field_initial

    @classmethod
    def get_initial(cls, request):
        return {cls.fieldname: cls.get_initial_value(request)}

    def _store_preference(self, request, namespace):
        _, success = get_or_update_preference(
            request,
            self.get_querydict_for_value(request),
            namespace,
            self.fieldname,
        )
        return success

    def _store_in_session(self, request):
        if self.is_valid():
            value = self.get_clean_value(request)
            request.session[self.fieldname] = value
            return True
        return False

    def store(self, request):
        """Store value of field_name

        ``request`` is used to store preferences or in session, and to add
        messages.

        Returns:

        - ``None`` if not implemented
        - ``True`` if implemented and successfully stored
        - ``False`` if implemented but storing was not possible
        """
        # Use self.get_clean_value() to get value to store
        return None


class SearchMixin:
    def filter(self, queryset, request):
        _input = self.get_clean_value(request)
        if _input:
            queryset = queryset.filter(**{self.lookup: _input})
        return queryset


class HasTextSearchMixin:
    def filter(self, queryset, request):
        _input = self.get_clean_value(request)
        if _input == "yes":
            queryset = queryset.exclude(**{self.lookup: ""})
        elif _input == "no":
            queryset = queryset.filter(**{self.lookup: ""})
        return queryset

src/argus/htmx/incident/forms/incident_actions.py
from django import forms


class AckForm(forms.Form):
    description = forms.CharField()
    expiration = forms.DateTimeField(required=False)


class DescriptionOptionalForm(forms.Form):
    "For closing/reopening"

    description = forms.CharField(required=False)


class EditTicketUrlForm(forms.Form):
    ticket_url = forms.URLField(required=False)


class AddTicketUrlForm(forms.Form):
    ticket_url = forms.URLField(required=True)

src/argus/htmx/incident/views.py
from __future__ import annotations

import logging
from collections.abc import Iterable
from datetime import datetime
from urllib.parse import urlencode
from typing import Optional, Any

from django import forms
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.utils.timezone import now as tznow
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.core.paginator import Paginator
from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
    JsonResponse,
    QueryDict,
)
from django_htmx.http import HttpResponseClientRefresh, retarget

from argus.incident.models import Incident, Tag
from argus.incident.ticket.utils import get_ticket_plugin_path
from argus.incident.ticket.base import TicketPluginException
from argus.notificationprofile.models import Filter
from argus.util.datetime_utils import make_aware

from ..request import HtmxHttpRequest

from .columns import get_incident_table_columns
from .utils import get_filter_function
from .forms.incident_filters import IncidentListForm, SortForm, SORT_DEFAULT
from .forms.incident_actions import AckForm, DescriptionOptionalForm, EditTicketUrlForm, AddTicketUrlForm
from ..utils import (
    single_autocreate_ticket_url_queryset,
    bulk_change_incidents,
    bulk_ack_queryset,
    bulk_close_queryset,
    bulk_reopen_queryset,
    bulk_change_ticket_url_queryset,
)

User = get_user_model()
LOG = logging.getLogger(__name__)


# Map request trigger to parameters for incidents update
INCIDENT_UPDATE_ACTIONS = {
    "ack": (AckForm, bulk_ack_queryset),
    "close": (DescriptionOptionalForm, bulk_close_queryset),
    "reopen": (DescriptionOptionalForm, bulk_reopen_queryset),
    "update-ticket": (EditTicketUrlForm, bulk_change_ticket_url_queryset),
    "add-ticket": (AddTicketUrlForm, bulk_change_ticket_url_queryset),
    "autocreate-ticket": (None, single_autocreate_ticket_url_queryset),
}


def prefetch_incident_daughters():
    return Incident.objects.select_related("source").prefetch_related(
        "incident_tag_relations",
        "incident_tag_relations__tag",
        "events",
        "events__ack",
        "planned_maintenance_tasks",
    )


# fetch with htmx
@require_GET
def incident_detail(request, pk: int):
    incident = get_object_or_404(Incident, id=pk)
    context = {
        "incident": incident,
        "page_title": str(incident),
        "autocreate_ticket": bool(get_ticket_plugin_path()),
    }
    return render(request, "htmx/incident/incident_detail.html", context=context)


def get_incident_ids_to_update(request):
    return request.POST.getlist("incident_ids", [])


def get_form(request, formclass: Optional[forms.Form]):
    formdata = request.POST or None
    form = None
    if formclass and formdata:
        form = formclass(formdata)
    return form


@require_POST
def incident_update(request: HtmxHttpRequest, action: str):
    LOG = logging.getLogger(__name__ + ".incident_update")
    try:
        formclass, callback_func = INCIDENT_UPDATE_ACTIONS[action]
    except KeyError:
        LOG.error("Unrecognized action name when updating incidents.")
        return HttpResponseBadRequest("Invalid update action")
    incident_ids = get_incident_ids_to_update(request)
    if not incident_ids:
        return HttpResponseClientRefresh()

    if action == "autocreate-ticket":
        try:
            single_autocreate_ticket_url_queryset(request, incident_ids, {"timestamp": tznow()})
        except TicketPluginException as e:
            messages.error(request, str(e))
        return HttpResponseClientRefresh()

    form = get_form(request, formclass)
    if form.is_valid():
        bulk_change_incidents(request, incident_ids, form.cleaned_data, callback_func)
    else:
        messages.error(request, form.errors)
    return HttpResponseClientRefresh()


@require_GET
def filter_form(request: HtmxHttpRequest):
    LOG = logging.getLogger(__name__ + ".filter_form")
    request.session["selected_filter"] = None
    incident_list_filter = get_filter_function()
    filter_form, _ = incident_list_filter(request, None)
    context = {"filter_form": filter_form}
    LOG.debug("GET: %s", request.GET)
    return render(request, "htmx/incident/_incident_filterbox.html", context=context)


@require_POST
def create_filter(request: HtmxHttpRequest):
    from argus.htmx.incident.filter import create_named_filter

    filter_name = request.POST.get("filter_name", None)
    incident_list_filter = get_filter_function()
    filter_form, _ = incident_list_filter(request, None)
    if filter_name and filter_form.is_valid():
        filterblob = filter_form.to_filterblob()
        _, filter_obj = create_named_filter(request, filter_name, filterblob)
        if filter_obj:
            request.session["selected_filter"] = str(filter_obj.id)
            return HttpResponseClientRefresh()
    messages.error(request, "Failed to create filter")
    return HttpResponseBadRequest()


@require_POST
def update_filter(request: HtmxHttpRequest, pk: int):
    filter_obj = get_object_or_404(Filter, id=pk)
    if not filter_obj.editable_by(request.user):
        return HttpResponseForbidden(f"{request.user} may not alter this filter")
    incident_list_filter = get_filter_function()
    filter_form, _ = incident_list_filter(request, None)
    if filter_form.is_valid():
        filterblob = filter_form.to_filterblob()
        filter_obj.filter = filterblob
        filter_obj.save()

        # Immediately select the newly updated filter - keep or not?
        # request.session["selected_filter"] = str(filter_obj.id)

        return HttpResponseClientRefresh()
    messages.error(request, f"Failed to update filter '{filter_obj.name}'.")
    return HttpResponseBadRequest()


@require_POST
def delete_filter(request: HtmxHttpRequest, pk: int):
    filter_obj = get_object_or_404(Filter, id=pk)
    if not filter_obj.editable_by(request.user):
        return HttpResponseForbidden(f"{request.user} may not alter this filter")
    deleted_id = filter_obj.delete()
    if deleted_id:
        if request.session.get("selected_filter") == str(pk):
            request.session["selected_filter"] = None
        return HttpResponseClientRefresh()


@require_GET
def get_existing_filters(request: HtmxHttpRequest):
    existing_filters = Filter.objects.all().filter(user=request.user)
    if existing_filters:
        context = {"filters": existing_filters.order_by("name")}
        if request.htmx.target == "delete-filter-items":
            context.update({"action": "delete"})
        return render(request, "htmx/incident/_existing_filters.html", context=context)
    else:
        return render(request, "htmx/incident/responses/empty_list_item.html", context={"message": "No filters found."})


@require_GET
def filter_select(request: HtmxHttpRequest):
    filter_id = request.GET.get("filter", None)
    if filter_id and get_object_or_404(Filter, id=filter_id):
        request.session["selected_filter"] = filter_id
        incident_list_filter = get_filter_function()
        filter_form, _ = incident_list_filter(request, None)
        context = {"filter_form": filter_form}
        return render(request, "htmx/incident/_incident_filterbox.html", context=context)
    else:
        request.session["selected_filter"] = None
        if request.htmx.trigger:
            incident_list_filter = get_filter_function()
            filter_form, _ = incident_list_filter(request, None, use_empty_filter=True)
            context = {"filter_form": filter_form}
            return render(request, "htmx/incident/_incident_filterbox.html", context=context)
        else:
            return retarget(HttpResponse(), "#incident-filter-select")


def dedupe_querydict(querydict: QueryDict):
    # if in doubt, use the biggest hammer *sigh*
    qd = QueryDict(mutable=True)
    for key, value in querydict.items():
        value = querydict.getlist(key)  # value is always a list of strings
        value = filter(None, value)  # strip away empty strings
        value = list(set(value))  # dedupe list of strings
        if not value:
            continue
        qd.setlist(key, value)  # safely add to query dict
    qd._mutable = False  # make read only
    return qd


def add_param_to_querydict(querydict: QueryDict, key: str, value: Any):
    "Set key to value if missing from querydict"
    qd = querydict.copy()
    if value is None:
        return querydict
    if key not in qd:
        if isinstance(value, Iterable):
            if not value:
                return querydict
            if isinstance(value, str):
                value = [value]
            else:
                qd[key] = list(value)
        else:
            value = [str(value)]
        qd.setlist(key, value)
        qd._mutable = False
        return qd
    return querydict


class SearchForm(forms.Form):
    search = forms.CharField(required=False)


@require_GET
def search_tags(request):
    query = request.GET.get("q")

    if not query:
        return JsonResponse({"results": []})

    if Tag.TAG_DELIMITER in query:
        key, value = Tag.split(query)
        tags = Tag.objects.filter(key=key, value__icontains=value)[:20]
    else:
        tags = Tag.objects.filter(key__icontains=query)[:20]

    options = [{"id": str(tag), "text": str(tag)} for tag in tags]

    return JsonResponse({"results": options})


@require_GET
def incident_list(request: HtmxHttpRequest) -> HttpResponse:
    LOG = logging.getLogger(__name__ + ".incident_list")
    LOG.debug("GET at start: %s", request.GET)
    request.GET = dedupe_querydict(request.GET)
    LOG.debug("after dedupe: %s", request.GET)

    preferences = request.user.get_preferences_context()
    column_layout_name = preferences["argus_htmx"]["incidents_table_column_name"]
    columns = get_incident_table_columns(column_layout_name)

    # Handle sorting

src/argus/htmx/templates/htmx/incident/cells/_incident_ack_icon.html
<!-- htmx/incident/cells/_incident_ack_icon.html -->
{% if incident.acked %}
  <span class="text-success text-lg tooltip tooltip-bottom w-5"
        data-tip="Acked">
    <i class="fa-solid fa-eye"></i>
  </span>
{% else %}
  <span class="text-warning text-lg tooltip tooltip-bottom w-5"
        data-tip="Unacked">
    <i class="fa-solid fa-eye-slash"></i>
  </span>
{% endif %}

src/argus/htmx/templates/htmx/incident/cells/_incident_actions.html
<!-- htmx/incident/cells/_incident_actions.html -->
<p>X</p>

src/argus/htmx/templates/htmx/incident/cells/_incident_checkbox.html
<!-- htmx/incident/cells/_incident_checkbox.html -->
<label for="select-incident-{{ incident.pk }}" class="sr-only">Select all visible</label>
<input id="select-incident-{{ incident.pk }}"
       hx-preserve
       type="checkbox"
       autocomplete="off"
       class="row-select checkbox checkbox-sm checkbox-primary border"
       hx-on:change="event.target.checked ? htmx.find('.tab-select').checked = event.target.checked : null;"
       name="incident_ids"
       value="{{ incident.pk }}">

src/argus/htmx/templates/htmx/incident/cells/_incident_color_status.html
<!-- htmx/incident/cells/_incident_color_status.html -->
<td class="w-4 p-0 {% if incident.open and not incident.acked %}bg-error{% elif not incident.open and incident.acked %}bg-success{% endif %}">
</td>

src/argus/htmx/templates/htmx/incident/cells/_incident_combined_status_icon.html
<!-- htmx/incident/cells/_incident_combined_status_icon.html -->
<div class="flex justify-between gap-2 w-fit">
  {% include "htmx/incident/cells/_incident_status_icon.html" %}
  {% include "htmx/incident/cells/_incident_ack_icon.html" %}
</div>

src/argus/htmx/templates/htmx/incident/cells/_incident_end_time.html
<!-- htmx/incident/cells/_incident_end_time.html -->
{% if incident.end_time and not incident.open %}
  {{ incident.end_time|date:preferences.argus_htmx.datetime_format }}
{% endif %}

src/argus/htmx/templates/htmx/incident/cells/_incident_filterable_column_header_content.html
<!-- htmx/incident/cells/_incident_filterable_column_header_content.html -->
{% load argus_htmx widget_tweaks %}
{% with field=form|get_form_field:fieldname %}
  <div class="flex items-center gap-1">
    <span id="{{ field.name }}-label">{{ column.label }}</span>
    {% include "htmx/incident/cells/_incident_sort_button.html" %}
    {# Filter dropdown #}
    <div id="{{ column.name }}-dropdown" class="dropdown dropdown-end">
      <button type="button"
              tabindex="0"
              aria-label="Filter by {{ column.label|lower }}"
              aria-controls="{{ column.name }}-dropdown-content"
              class="filter-btn btn btn-xs {% if field.value %} btn-primary {% else %} btn-ghost text-primary {% endif %} min-h-4 h-4"
              {% if dummy_column %}disabled{% endif %}>
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
      <div id="{{ column.name }}-dropdown-content"
           class="dropdown-content bg-base-100 p-2 mt-1 rounded-lg shadow border border-primary z-10"
           tabindex="-1">
        <form class="incident-list-param">
          <div aria-labelledby="{{ field.name }}-label">
            {# djlint:off #}
            {% if not dummy_column %}
              {% url 'htmx:incident-list' as incident_list_url %}
              {% render_field field hx-get=incident_list_url hx-include=".incident-list-param" hx-target="#table-body" hx-select="#table-body" hx-select-oob="#table-footer" hx-swap="outerHTML" hx-push-url="true" hx-indicator="#incident-list .htmx-indicator" hx-trigger="change delay:500ms" %}
            {% else %}
              {{ field }}
            {% endif %}
            {# djlint:on #}
          </div>
        </form>
      </div>
    </div>
  </div>
{% endwith %}
<script>
(function() {
  const dropdown = document.querySelector('#{{ column.name }}-dropdown');
  const filterBtn = dropdown.querySelector('.filter-btn');

  filterBtn.addEventListener('focus', function() {
    const content = dropdown.querySelector('.dropdown-content');
    const rect = content.getBoundingClientRect();

    if (rect.right > window.innerWidth) {
      dropdown.classList.add('dropdown-end');
    } else if (rect.left < 0) {
      dropdown.classList.remove('dropdown-end');
    }
  });

  dropdown.addEventListener('htmx:afterRequest', function() {
    const field = dropdown.querySelector('input:not([type="hidden"]), select');
    if (field?.value) {
      filterBtn.classList.add('btn-primary');
      filterBtn.classList.remove('btn-ghost', 'text-primary');
    } else {
      filterBtn.classList.remove('btn-primary');
      filterBtn.classList.add('btn-ghost', 'text-primary');
    }
  });
})();
</script>

src/argus/htmx/templates/htmx/incident/cells/_incident_level_compact.html
<!-- htmx/templates/htmx/incident/cells/_incident_level_compact.html -->
{% load argus_htmx %}
<div class="flex justify-center">
  <span class="badge text-nowrap tooltip tooltip-bottom bg-severity-primary-{{ incident.level }} border-severity-primary-{{ incident.level }} text-severity-secondary-{{ incident.level }}"
        data-tip="{{ incident.level|pp_level }}">{{ incident.level }}</span>
</div>

src/argus/htmx/templates/htmx/incident/cells/_incident_pk.html
<!-- htmx/templates/htmx/incident/cells/_incident_pk.html -->
<a class="link" href="{% url 'htmx:incident-detail' pk=incident.pk %}">{{ incident.pk }}</a>

src/argus/htmx/templates/htmx/incident/cells/_incident_source.html
<!-- htmx/incident/cells/_incident_source.html -->
{{ incident.source.name }}

src/argus/htmx/templates/htmx/incident/cells/_incident_start_time_header.html
<!-- htmx/incident/cells/_incident_start_time_header.html -->
<div class="min-w-48">Timestamp</div>

src/argus/htmx/templates/htmx/incident/cells/_incident_status.html
<!-- htmx/templates/htmx/incident/cells/_incident_status.html -->
{% if incident.open %}
  <span class="badge badge-error">Open</span>
{% else %}
  <span class="badge badge-success">Closed</span>
{% endif %}

src/argus/htmx/templates/htmx/incident/cells/_incident_tag.html
<!-- htmx/incident/cells/_incident_tag.html -->
{% load argus_htmx %}
{{ incident|tagvalues:column.context.tag|first }}

src/argus/htmx/templates/htmx/incident/cells/_incident_tags.html
<!-- htmx/incident/cells/_incident_tags.html -->
{% load argus_htmx %}
<div class="flex gap-1 flex-wrap">
  {% for tag in incident.deprecated_tags %}
    <span class="badge badge-xs badge-neutral-content badge-outline  h-auto text-wrap break-all text-center text-xs">
      {# djlint:off #}
      {{ tag.key }}{{ tag.TAG_DELIMITER }}{% if tag.value|is_valid_url %}<a href="{{ tag.value }}" target="_blank" rel="noreferrer">{{ tag.value }}</a>{% else %}{{ tag.value }}{% endif %}
      {# djlint:on #}
    </span>
  {% endfor %}
</div>